name: IE Python Checks
# TODO: add for IE API, wheels
on:
  workflow_dispatch:
  push:
    paths:
      - 'inference-engine/ie_bridges/python/sample/**'
  pull_request:
    paths:
      - 'inference-engine/ie_bridges/python/sample/**'
jobs:
  linters:
    runs-on: ubuntu-18.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: python -m pip install -r inference-engine/ie_bridges/python/sample/requirements_dev.txt
      - name: Run Flake
        run: python -m flake8 ./ --config=setup.cfg --show-source 
        working-directory: inference-engine/ie_bridges/python/sample
      - name: Run MyPy 
        run: python -m mypy ./ --config-file ./setup.cfg --show-error-context --show-column-numbers --pretty
        working-directory: inference-engine/ie_bridges/python/sample      
      - name: Run Bandit
        run: python -m bandit -r ./ -f screen
        working-directory: inference-engine/ie_bridges/python/sample